### ISSUE TITLE
how to edit the parameter (-d DIS  Position range near start codon or stop codon)?

### ISSUE THREAD

**Issue by shwdmsh** [zhpn1024/ribotish#14]
Hi,
If I want to get the range of -20,40 near start codon or stop codon ,how to do ?
My command as follows:
ribotish quality -b test.sort.bam -p 8 -l 145,151 -d 60 --nom0 -g genomic.gtf
some error information:IndexError: tuple index out of range

**Comment by zhpn1024** [comment]
Try `-d -20,40`.
Do you use the length ~150nt? It is suggested to remove adaptors before alignment.

**Comment by shwdmsh** [comment]
Hi, the test seq length is ~150nt, which is the RNA_seq data.
When I use Riboseq data,the test2 seq length is about 28nt.
I use the command :ribotish quality -b test.sort.bam -p 8 -d -20,40 -g genomic.gtf 
some error information:ribotish quality: error: argument -d: expected one argument
However,I use the command : ribotish quality -b test.sort.bam -p 8  -g genomic.gtf, I can get the quality pdf file

**Comment by zhpn1024** [comment]
The problem may be that python argparse take the minus character '-' in '-20,40' as sign of another option parameter instead of argument value.
Try `-d-20,40` (no space after d) or `-d ' -20,40'` (add commas and another space before '-').
















在 2021-03-17 10:35:08，"shwdmsh" ***@***.***> 写道：

Hi, the test seq length is ~150nt, which is the RNA_seq data.
When I use Riboseq data,the test2 seq length is about 28nt.
I use the command :ribotish quality -b test.sort.bam -p 8 -d -20,40 -g genomic.gtf
some error information:ribotish quality: error: argument -d: expected one argument
However,I use the command : ribotish quality -b test.sort.bam -p 8 -g genomic.gtf, I can get the quality pdf file
