### ISSUE TITLE
-- inprofile still requires bam 

### ISSUE THREAD

**Issue by ericmalekos** [zhpn1024/ribotish#42]
Hello, 

Im trying to run Ribotish with generated transprofile but it seems to require the BAMs be input as well:

```
$ ribotish predict \
  -g custom_lncRNA.gtf \
  -f GRCm39.primary_assembly.genome.fa \
  -o lncRNA_ORFs.tsv \
  --inprofile merged.transprofile
No bam file input!

$ ribotish predict \
  -b merged.bam 
  -g custom_lncRNA.gtf \
  -f GRCm39.primary_assembly.genome.fa \
  -o lncRNA_ORFs.tsv \
  --inprofile merged.transprofile
No offset parameter file found for LPS_merged.bam. Using default offset (12).
No input TIS data!
Mon Dec  2 14:05:03 2024 Predicting...
Mon Dec  2 14:17:07 2024 Checking overlap with known CDS..
Mon Dec  2 14:17:07 2024 BH correcting...
Mon Dec  2 14:17:07 2024 Done! Time used: 723.634901047 s.
```

Is the bam information being used for something? I thought it would just be performing statistical testing using the transprofile?

**Comment by zhpn1024** [comment]
Yes, actually the bam data is not used if inprofile is provided. Since the inprofile option was added later, the requirement of bam input was not adjusted. 
The bam options are used to initialize the input mode of the predict module, for example whether there is TI data, or whether tis2ribo option need to be set.

**Comment by ericmalekos** [comment]
I see, I will just make a minimal bam file for this use case as it is not use anyway. Thank you!
